# -*- coding: utf-8 -*-
############################################################
#
# Autogenerated by the KBase type compiler -
# any changes made here will be overwritten
#
############################################################

from __future__ import print_function
# the following is a hack to get the baseclient to import whether we're in a
# package or not. This makes pep8 unhappy hence the annotations.
try:
    # baseclient and this client are in a package
    from .baseclient import BaseClient as _BaseClient  # @UnusedImport
except:
    # no they aren't
    from baseclient import BaseClient as _BaseClient  # @Reimport
import time


class KBaseReportPy(object):

    def __init__(
            self, url=None, timeout=30 * 60, user_id=None,
            password=None, token=None, ignore_authrc=False,
            trust_all_ssl_certificates=False,
            auth_svc='https://kbase.us/services/authorization/Sessions/Login',
            service_ver='release',
            async_job_check_time_ms=100, async_job_check_time_scale_percent=150, 
            async_job_check_max_time_ms=300000):
        if url is None:
            raise ValueError('A url is required')
        self._service_ver = service_ver
        self._client = _BaseClient(
            url, timeout=timeout, user_id=user_id, password=password,
            token=token, ignore_authrc=ignore_authrc,
            trust_all_ssl_certificates=trust_all_ssl_certificates,
            auth_svc=auth_svc,
            async_job_check_time_ms=async_job_check_time_ms,
            async_job_check_time_scale_percent=async_job_check_time_scale_percent,
            async_job_check_max_time_ms=async_job_check_max_time_ms)

    def _check_job(self, job_id):
        return self._client._check_job('KBaseReportPy', job_id)

    def _create_submit(self, params, context=None):
        return self._client._submit_job(
             'KBaseReportPy.create', [params],
             self._service_ver, context)

    def create(self, params, context=None):
        """
        Function signature for the create() method -- generate a report for an app run.
        create_extended() is the preferred method if you have html_links and
        file_links, but this is still provided for backwards compatibility.
        :param params: instance of type "CreateParams" (* Parameters for the
           create() method * Pass in *either* workspace_name or workspace_id
           -- only one is needed * Required arguments: *    int workspace_id
           - needed if workspace_name is blank. Preferred as its immutable. *
           string workspace_name - needed if workspace_id is blank. Note that
           this may change. *    Report report) -> structure: parameter
           "report" of type "Report" (* A simple Report of a method run in
           KBase. * Provides a fixed-width, text-based summary message, a
           list of warnings, * and a list of objects created. * Required
           arguments: *     string text_message - Readable plain-text report
           message * @optional warnings file_links html_links direct_html
           direct_html_link_index * @metadata ws length(warnings) as Warnings
           * @metadata ws length(text_message) as Message Length * @metadata
           ws length(objects_created) as Objects Created) -> structure:
           parameter "text_message" of String, parameter "warnings" of list
           of String, parameter "objects_created" of list of type
           "WorkspaceObject" (* Represents a Workspace object with some brief
           description text * that can be associated with the object. *
           Required arguments: *     ws_id ref - workspace ID * @optional
           description) -> structure: parameter "ref" of type "ws_id" (*
           Workspace ID reference - eg. 'ws/id/ver' * @id ws), parameter
           "description" of String, parameter "file_links" of list of type
           "LinkedFile" (* Represents a file or html archive that the report
           should link to * Used in Report and the create() function *
           Required arguments: *     handle_ref handle - Handle ID *    
           string name - Plain-text name of the file (shown to the user) *   
           string URL - shock URL and ID (`shock['handle']['url'] + '/node/'
           + shock['handle']['id']`) * @optional description label) ->
           structure: parameter "handle" of type "handle_ref" (* Reference to
           a handle ID * @id handle), parameter "description" of String,
           parameter "name" of String, parameter "label" of String, parameter
           "URL" of String, parameter "html_links" of list of type
           "LinkedFile" (* Represents a file or html archive that the report
           should link to * Used in Report and the create() function *
           Required arguments: *     handle_ref handle - Handle ID *    
           string name - Plain-text name of the file (shown to the user) *   
           string URL - shock URL and ID (`shock['handle']['url'] + '/node/'
           + shock['handle']['id']`) * @optional description label) ->
           structure: parameter "handle" of type "handle_ref" (* Reference to
           a handle ID * @id handle), parameter "description" of String,
           parameter "name" of String, parameter "label" of String, parameter
           "URL" of String, parameter "direct_html" of String, parameter
           "direct_html_link_index" of Long, parameter "workspace_name" of
           String, parameter "workspace_id" of Long
        :returns: instance of type "ReportInfo" (* The reference to the saved
           KBaseReport. This is the return object for * both create() and
           create_extended() * Required arguments: *    ws_id ref *    string
           name) -> structure: parameter "ref" of type "ws_id" (* Workspace
           ID reference - eg. 'ws/id/ver' * @id ws), parameter "name" of
           String
        """
        job_id = self._create_submit(params, context)
        async_job_check_time = self._client.async_job_check_time
        while True:
            time.sleep(async_job_check_time)
            async_job_check_time = (async_job_check_time *
                self._client.async_job_check_time_scale_percent / 100.0)
            if async_job_check_time > self._client.async_job_check_max_time:
                async_job_check_time = self._client.async_job_check_max_time
            job_state = self._check_job(job_id)
            if job_state['finished']:
                return job_state['result'][0]

    def _create_extended_report_submit(self, params, context=None):
        return self._client._submit_job(
             'KBaseReportPy.create_extended_report', [params],
             self._service_ver, context)

    def create_extended_report(self, params, context=None):
        """
        Create a report for the results of an app run -- handles file and html zipping/uploading
        If you are using html_links or file_links, this will be more user-friendly than create()
        :param params: instance of type "CreateExtendedReportParams" (*
           Parameters used to create a more complex report with file and html
           links * * All parameters are optional. * * string message - Simple
           text message to store in report object * list<WorkspaceObject>
           objects_created - List of result workspace objects that this app *
           has created. They will get linked in the report view. *
           list<string> warnings - A list of plain-text warning messages *
           list<File> html_links - A list of paths or shock IDs pointing to
           html files or directories. *     if you pass in paths, they will
           be zipped and uploaded * int direct_html_link_index - Index in
           html_links to set the direct/default view in the *     report
           (ignored if direct_html is present). * string direct_html - simple
           html text that will be rendered within the report widget *     (do
           not use both this and html_links -- use one or the other) *
           list<File> file_links - a list of file paths or shock node IDs.
           Allows the user to *     specify files that the report widget
           should link for download. * string report_object_name - name to
           use for the report object *     (will be auto-generated if
           unspecified) * html_window_height - fixed height in pixels of the
           html window for the report * summary_window_height - fixed height
           in pixels of the summary window for the report * string
           workspace_name - name of workspace where object should be saved *
           int workspace_id - id of workspace where object should be saved *
           * @metadata ws length(warnings) as Warnings * @metadata ws
           length(text_message) as Message Length * @metadata ws
           length(objects_created) as Objects Created * @metadata ws
           length(html_links) as HTML Links * @metadata ws length(file_links)
           as File Links * @optional message objects_created warnings
           html_links direct_html direct_html_link_index file_links
           report_object_name html_window_height summary_window_height) ->
           structure: parameter "message" of String, parameter
           "objects_created" of list of type "WorkspaceObject" (* Represents
           a Workspace object with some brief description text * that can be
           associated with the object. * Required arguments: *     ws_id ref
           - workspace ID * @optional description) -> structure: parameter
           "ref" of type "ws_id" (* Workspace ID reference - eg. 'ws/id/ver'
           * @id ws), parameter "description" of String, parameter "warnings"
           of list of String, parameter "html_links" of list of type "File"
           (* A file to be linked or uploaded for the report. In
           extended_report(), * this will get converted into a lower-level
           LinkedFile before uploading * Pass in *either* a shock_id or a
           path. If a path is given, then the file * will be uploaded. *
           Required arguments: *     string path - only if shock_id is
           absent. Can be a file or dir path. *     string shock_id - only if
           path is absent. *     string name - plain-text file name -- shown
           to the user. * @optional description) -> structure: parameter
           "path" of String, parameter "shock_id" of String, parameter "name"
           of String, parameter "description" of String, parameter
           "direct_html" of String, parameter "direct_html_link_index" of
           Long, parameter "file_links" of list of type "File" (* A file to
           be linked or uploaded for the report. In extended_report(), * this
           will get converted into a lower-level LinkedFile before uploading
           * Pass in *either* a shock_id or a path. If a path is given, then
           the file * will be uploaded. * Required arguments: *     string
           path - only if shock_id is absent. Can be a file or dir path. *   
           string shock_id - only if path is absent. *     string name -
           plain-text file name -- shown to the user. * @optional
           description) -> structure: parameter "path" of String, parameter
           "shock_id" of String, parameter "name" of String, parameter
           "description" of String, parameter "report_object_name" of String,
           parameter "html_window_height" of Double, parameter
           "summary_window_height" of Double, parameter "workspace_name" of
           String, parameter "workspace_id" of Long
        :returns: instance of type "ReportInfo" (* The reference to the saved
           KBaseReport. This is the return object for * both create() and
           create_extended() * Required arguments: *    ws_id ref *    string
           name) -> structure: parameter "ref" of type "ws_id" (* Workspace
           ID reference - eg. 'ws/id/ver' * @id ws), parameter "name" of
           String
        """
        job_id = self._create_extended_report_submit(params, context)
        async_job_check_time = self._client.async_job_check_time
        while True:
            time.sleep(async_job_check_time)
            async_job_check_time = (async_job_check_time *
                self._client.async_job_check_time_scale_percent / 100.0)
            if async_job_check_time > self._client.async_job_check_max_time:
                async_job_check_time = self._client.async_job_check_max_time
            job_state = self._check_job(job_id)
            if job_state['finished']:
                return job_state['result'][0]

    def status(self, context=None):
        job_id = self._client._submit_job('KBaseReportPy.status', 
            [], self._service_ver, context)
        async_job_check_time = self._client.async_job_check_time
        while True:
            time.sleep(async_job_check_time)
            async_job_check_time = (async_job_check_time *
                self._client.async_job_check_time_scale_percent / 100.0)
            if async_job_check_time > self._client.async_job_check_max_time:
                async_job_check_time = self._client.async_job_check_max_time
            job_state = self._check_job(job_id)
            if job_state['finished']:
                return job_state['result'][0]
